.TH "GG2" "1" 
.SH "NAME" 
gghist \(em History Viewer for Instant Messaging Client 
.SH "DESCRIPTION" 
.PP 
This is a history viewer provied as a plugin for GNU Gadu. 
 
.SH "BUG REPORTS" 
.PP 
If you find a bug, please submit it on project mailing list. 
Before filing a bug,  
please check the latest CVS version and if the bug was not already submited. 
 
.SH "SEE ALSO" 
.PP 
http://gadu.gnu.pl 
.SH "AUTHOR" 
.PP 
The gghist was written by Igor Popik, Marcin Krzyzanowski and others. 
 
.PP 
Permission is granted to copy, distribute and/or modify under 
the terms of the GNU General Public License, Version 2 any  
later version published by the Free Software Foundation. 
 
.\" created by instant / docbook-to-man, Sun 15 Oct 2006, 12:34 
