/* $Id: plugin_xosd.h,v 1.4 2003/07/05 18:27:15 shaster Exp $ */
#ifndef PLUGIN_XOSD_H
#define PLGUIN_XOSD_H 1

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#define GGADU_XOSD_WELCOME_STRING "GNU Gadu 2"

#define GGADU_XOSD_DEFAULT_FONT "-misc-fixed-bold-r-*-*-15-*-*-*-*-*-*-2"
#define GGADU_XOSD_DEFAULT_COLOUR "#FFFF00"
#define GGADU_XOSD_DEFAULT_NUMLINES 5
#define GGADU_XOSD_DEFAULT_TIMEOUT 5
#define GGADU_XOSD_DEFAULT_SHADOW_OFFSET 1
#define GGADU_XOSD_DEFAULT_HORIZONTAL_OFFSET 0
#define GGADU_XOSD_DEFAULT_VERTICAL_OFFSET 0
#define GGADU_XOSD_DEFAULT_ALIGN XOSD_center
#define GGADU_XOSD_DEFAULT_POS XOSD_top

enum
{
    GGADU_XOSD_CONFIG_COLOUR,
    GGADU_XOSD_CONFIG_NUMLINES,
    GGADU_XOSD_CONFIG_FONT,
    GGADU_XOSD_CONFIG_TIMEOUT,
    GGADU_XOSD_CONFIG_SHADOW_OFFSET,
    GGADU_XOSD_CONFIG_HORIZONTAL_OFFSET,
    GGADU_XOSD_CONFIG_VERTICAL_OFFSET,
    GGADU_XOSD_CONFIG_ALIGN,
    GGADU_XOSD_CONFIG_POS,
    GGADU_XOSD_CONFIG_TIMESTAMP
};

gint set_configuration(void);

#endif /* PLUGIN_XOSD_H */
