/* $Id */
#include <glib.h>

gint set_configuration ();

enum {
    GGADU_XOSD_CONFIG_COLOUR,
    GGADU_XOSD_CONFIG_NUMLINES,
    GGADU_XOSD_CONFIG_FONT,
    GGADU_XOSD_CONFIG_TIMEOUT,
    GGADU_XOSD_CONFIG_SHADOW_OFFSET,
    GGADU_XOSD_CONFIG_ALIGN,
    GGADU_XOSD_CONFIG_POS,
    GGADU_XOSD_CONFIG_SCROLLLINES,
    GGADU_XOSD_CONFIG_TIMESTAMP
};

gint NUMLINES;
gchar *FONT;
gchar *COLOUR;
gint TIMEOUT;
gint SHADOW_OFFSET;
gint SCROLLLINES;
gint ALIGN;
gint POS;
